//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int WordID { get; set; }
        public string WordTurkish { get; set; }
        public string WordEnglish { get; set; }
        public Nullable<int> WordTypeID { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
